# Generated by Django 3.2 on 2022-05-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_membership_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='member',
        ),
    ]
